# Generated by Django 4.2.7 on 2026-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms_app', '0003_teacherotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacherotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
